export const GetArticles = "https://localhost:44321/api/blog/articles"
export const GetPhotos = "https://localhost:44321/api/blog/photos"
export const GetUsers = "https://localhost:44321/api/blog/users"
export const GetArticle ="https://localhost:44321/api/blog/articles"
export const Login ="https://localhost:44321/api/account/login"
export const Register ="https://localhost:44321/api/account/login"